/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SearchRouteImport } from './routes/search'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as BirthdayCakeSlugRouteImport } from './routes/birthday-cake.$slug'
import { Route as CategoryCategorySlugRouteImport } from './routes/category.$categorySlug'
import { Route as FlavourFlavourSlugRouteImport } from './routes/flavour.$flavourSlug'
import { Route as KidsCakeSlugRouteImport } from './routes/kids-cake.$slug'
import { Route as ManageSecretRouteImport } from './routes/manage.$secret'
import { Route as ProductProductSlugRouteImport } from './routes/product.$productSlug'
import { Route as WeddingCakeCodeRouteImport } from './routes/wedding-cake.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdayCakeSlugRoute = BirthdayCakeSlugRouteImport.update({
  id: '/birthday-cake/$slug',
  path: '/birthday-cake/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategorySlugRoute = CategoryCategorySlugRouteImport.update({
  id: '/category/$categorySlug',
  path: '/category/$categorySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavourFlavourSlugRoute = FlavourFlavourSlugRouteImport.update({
  id: '/flavour/$flavourSlug',
  path: '/flavour/$flavourSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsCakeSlugRoute = KidsCakeSlugRouteImport.update({
  id: '/kids-cake/$slug',
  path: '/kids-cake/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageSecretRoute = ManageSecretRouteImport.update({
  id: '/manage/$secret',
  path: '/manage/$secret',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductSlugRoute = ProductProductSlugRouteImport.update({
  id: '/product/$productSlug',
  path: '/product/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingCakeCodeRoute = WeddingCakeCodeRouteImport.update({
  id: '/wedding-cake/$code',
  path: '/wedding-cake/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/birthday-cake/$slug': typeof BirthdayCakeSlugRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/flavour/$flavourSlug': typeof FlavourFlavourSlugRoute
  '/kids-cake/$slug': typeof KidsCakeSlugRoute
  '/manage/$secret': typeof ManageSecretRoute
  '/product/$productSlug': typeof ProductProductSlugRoute
  '/wedding-cake/$code': typeof WeddingCakeCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/birthday-cake/$slug': typeof BirthdayCakeSlugRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/flavour/$flavourSlug': typeof FlavourFlavourSlugRoute
  '/kids-cake/$slug': typeof KidsCakeSlugRoute
  '/manage/$secret': typeof ManageSecretRoute
  '/product/$productSlug': typeof ProductProductSlugRoute
  '/wedding-cake/$code': typeof WeddingCakeCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/birthday-cake/$slug': typeof BirthdayCakeSlugRoute
  '/category/$categorySlug': typeof CategoryCategorySlugRoute
  '/flavour/$flavourSlug': typeof FlavourFlavourSlugRoute
  '/kids-cake/$slug': typeof KidsCakeSlugRoute
  '/manage/$secret': typeof ManageSecretRoute
  '/product/$productSlug': typeof ProductProductSlugRoute
  '/wedding-cake/$code': typeof WeddingCakeCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/search'
    | '/wishlist'
    | '/birthday-cake/$slug'
    | '/category/$categorySlug'
    | '/flavour/$flavourSlug'
    | '/kids-cake/$slug'
    | '/manage/$secret'
    | '/product/$productSlug'
    | '/wedding-cake/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/search'
    | '/wishlist'
    | '/birthday-cake/$slug'
    | '/category/$categorySlug'
    | '/flavour/$flavourSlug'
    | '/kids-cake/$slug'
    | '/manage/$secret'
    | '/product/$productSlug'
    | '/wedding-cake/$code'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/search'
    | '/wishlist'
    | '/birthday-cake/$slug'
    | '/category/$categorySlug'
    | '/flavour/$flavourSlug'
    | '/kids-cake/$slug'
    | '/manage/$secret'
    | '/product/$productSlug'
    | '/wedding-cake/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  WishlistRoute: typeof WishlistRoute
  BirthdayCakeSlugRoute: typeof BirthdayCakeSlugRoute
  CategoryCategorySlugRoute: typeof CategoryCategorySlugRoute
  FlavourFlavourSlugRoute: typeof FlavourFlavourSlugRoute
  KidsCakeSlugRoute: typeof KidsCakeSlugRoute
  ManageSecretRoute: typeof ManageSecretRoute
  ProductProductSlugRoute: typeof ProductProductSlugRoute
  WeddingCakeCodeRoute: typeof WeddingCakeCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthday-cake/$slug': {
      id: '/birthday-cake/$slug'
      path: '/birthday-cake/$slug'
      fullPath: '/birthday-cake/$slug'
      preLoaderRoute: typeof BirthdayCakeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categorySlug': {
      id: '/category/$categorySlug'
      path: '/category/$categorySlug'
      fullPath: '/category/$categorySlug'
      preLoaderRoute: typeof CategoryCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavour/$flavourSlug': {
      id: '/flavour/$flavourSlug'
      path: '/flavour/$flavourSlug'
      fullPath: '/flavour/$flavourSlug'
      preLoaderRoute: typeof FlavourFlavourSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids-cake/$slug': {
      id: '/kids-cake/$slug'
      path: '/kids-cake/$slug'
      fullPath: '/kids-cake/$slug'
      preLoaderRoute: typeof KidsCakeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$secret': {
      id: '/manage/$secret'
      path: '/manage/$secret'
      fullPath: '/manage/$secret'
      preLoaderRoute: typeof ManageSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productSlug': {
      id: '/product/$productSlug'
      path: '/product/$productSlug'
      fullPath: '/product/$productSlug'
      preLoaderRoute: typeof ProductProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-cake/$code': {
      id: '/wedding-cake/$code'
      path: '/wedding-cake/$code'
      fullPath: '/wedding-cake/$code'
      preLoaderRoute: typeof WeddingCakeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  WishlistRoute: WishlistRoute,
  BirthdayCakeSlugRoute: BirthdayCakeSlugRoute,
  CategoryCategorySlugRoute: CategoryCategorySlugRoute,
  FlavourFlavourSlugRoute: FlavourFlavourSlugRoute,
  KidsCakeSlugRoute: KidsCakeSlugRoute,
  ManageSecretRoute: ManageSecretRoute,
  ProductProductSlugRoute: ProductProductSlugRoute,
  WeddingCakeCodeRoute: WeddingCakeCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
